- type: loadout
  id: LoadoutSecurityUniformGrey
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - SecurityCadet
        - Warden
  items:
    - ClothingUniformJumpsuitSecGrey

- type: loadout
  id: LoadoutSecurityUniformJumpskirtSenior
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
  items:
    - ClothingUniformJumpskirtSeniorOfficer

- type: loadout
  id: LoadoutSecurityUniformJumpsuitSenior
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
  items:
    - ClothingUniformJumpsuitSeniorOfficer


- type: loadout
  id: LoadoutSecurityShoesJackboots
  category: Jobs
  cost: 1
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Detective
        - SecurityOfficer
        - SecurityCadet
        - Warden
        - HeadOfSecurity
  items:
    - ClothingShoesBootsJack
